# Generated by Django 4.2.2 on 2023-07-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=50, null=True, verbose_name='Name')),
                ('anons', models.CharField(default='default', max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(null=True, verbose_name='List')),
                ('date', models.DateTimeField(null=True, verbose_name='Date publications')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
